UPDATE IGNORE `bbtaxtype` SET `taxType` = '11-C - Occupational Tax and Registration Return for Wagering' WHERE (`id` = '1');
UPDATE IGNORE `bbtaxtype` SET `taxType` = '706-GS (D) - Generation-Skipping Transfer Tax Return for Distributions' WHERE (`id` = '2');
UPDATE IGNORE `bbtaxtype` SET `taxType` = '706-GS (T) - Generation-Skipping Transfer Tax Return for Terminations' WHERE (`id` = '3');
UPDATE IGNORE `bbtaxtype` SET `taxType` = '709 - United States Gift (and Generation-Skipping Transfer) Tax Return' WHERE (`id` = '4');
UPDATE IGNORE `bbtaxtype` SET `taxType` = '7200D - Branded Prescription Drug Fee' WHERE (`id` = '5');
UPDATE IGNORE `bbtaxtype` SET `taxType` = '730 - Monthly Tax Return for Wagers' WHERE (`id` = '6');
UPDATE IGNORE `bbtaxtype` SET `taxType` = '926 - Return by a U.S. Transferor of Property to a\nForeign Corporation' WHERE (`id` = '7');
UPDATE IGNORE `bbtaxtype` SET `taxType` = '940 - Employer’s Annual Federal Unemployment (FUTA) Tax Return' WHERE (`id` = '8');
UPDATE IGNORE `bbtaxtype` SET `taxType` = '941 - Employer’s Quarterly Federal Tax Return' WHERE (`id` = '9');
UPDATE IGNORE `bbtaxtype` SET `taxType` = '943 Employer’s Annual Federal Tax Return for Agricultural Employees' WHERE (`id` = '10');
UPDATE IGNORE `bbtaxtype` SET `taxType` = '944 Employer’s Annual Federal Tax Return' WHERE (`id` = '11');
UPDATE IGNORE `bbtaxtype` SET `taxType` = '945 Annual Return of Withheld Federal Income Tax' WHERE (`id` = '12');
UPDATE IGNORE `bbtaxtype` SET `taxType` = '990 Return of Organization Exempt from Income Tax' WHERE (`id` = '13');
UPDATE IGNORE `bbtaxtype` SET `taxType` = '990-BL Information and Initial Excise Tax Return for Black Lung Benefit Trusts and Certain Related Persons' WHERE (`id` = '14');
UPDATE IGNORE `bbtaxtype` SET `taxType` = '990-C U.S. Income Tax Return for Cooperative Associations' WHERE (`id` = '15');
UPDATE IGNORE `bbtaxtype` SET `taxType` = '990-PF Return of Private Foundation or Section 4947(a)(1)  Nonexempt Charitable Trust Treated as a Private Foundation' WHERE (`id` = '16');
UPDATE IGNORE `bbtaxtype` SET `taxType` = '990-T Exempt Organization Business Income Tax Return and proxy tax under section 6033(e)' WHERE (`id` = '17');
UPDATE IGNORE `bbtaxtype` SET `taxType` = '1041 Income Tax Return for Estates and Trusts' WHERE (`id` = '18');
UPDATE IGNORE `bbtaxtype` SET `taxType` = '1041-A U.S. Information Return Trust Accumulation of Charitable Amounts' WHERE (`id` = '19');
UPDATE IGNORE `bbtaxtype` SET `taxType` = '1042 Annual Withholding Tax Return for U.S. Source Income of Foreign Persons' WHERE (`id` = '20');
UPDATE IGNORE `bbtaxtype` SET `taxType` = '1065  U.S. Return of Partnership Income' WHERE (`id` = '21');
UPDATE IGNORE `bbtaxtype` SET `taxType` = '1066 Real Estate Mortgage Investment Conduit (REMIC) Income Tax Return' WHERE (`id` = '22');
UPDATE IGNORE `bbtaxtype` SET `taxType` = '1120 U.S. Corporation Income Tax Return' WHERE (`id` = '23');
UPDATE IGNORE `bbtaxtype` SET `taxType` = '1120-IC-DISC Interest Charge Domestic International Sales Corporation Return' WHERE (`id` = '24');
UPDATE IGNORE `bbtaxtype` SET `taxType` = '2290 Heavy Highway Vehicle Use Tax Return' WHERE (`id` = '25');
UPDATE IGNORE `bbtaxtype` SET `taxType` = '2438 Undistributed Capital Gains Tax Return' WHERE (`id` = '26');
UPDATE IGNORE `bbtaxtype` SET `taxType` = '3520 Annual Return To Report Transactions With Foreign Trusts and Receipt of Certain Foreign Gifts' WHERE (`id` = '27');
UPDATE IGNORE `bbtaxtype` SET `taxType` = '4720 Return of Certain Excise Taxes Under Chapters 41 and 42 of the Internal Revenue Code' WHERE (`id` = '28');
UPDATE IGNORE `bbtaxtype` SET `taxType` = '5227 Split-Interest Trust Information Return' WHERE (`id` = '29');
UPDATE IGNORE `bbtaxtype` SET `taxType` = '5329 Additional Taxes on Qualified Plans (including IRAs) and Other Tax Favored Accounts            ' WHERE (`id` = '30');
UPDATE IGNORE `bbtaxtype` SET `taxType` = '6069 Return of Excise Tax on Excess Contributions to Black Lung Benefit Trst-Section 4953 & Computation-Section 192 Deduction               ' WHERE (`id` = '31');
UPDATE IGNORE `bbtaxtype` SET `taxType` = '8288 U.S. Withholding Tax Return for Dispositions by Foreign Persons of U.S. Real Estate Property Interests           ' WHERE (`id` = '32');
UPDATE IGNORE `bbtaxtype` SET `taxType` = '8404 Interest Charge on DISC-Related Deferred Tax               ' WHERE (`id` = '33');
UPDATE IGNORE `bbtaxtype` SET `taxType` = '8612 Return of Excise Tax on Undistributed Income of Real Estate Investment Trusts           ' WHERE (`id` = '34');
UPDATE IGNORE `bbtaxtype` SET `taxType` = '8613 Return of Excise Tax on Undistributed Income of Regulated Investment Company     ' WHERE (`id` = '35');
UPDATE IGNORE `bbtaxtype` SET `taxType` = '8697 - Interest Computation Under the Look-Back Method  for Completed Long-Term Contracts               ' WHERE (`id` = '36');
UPDATE IGNORE `bbtaxtype` SET `taxType` = '8725 Excise Tax on Greenmail          ' WHERE (`id` = '37');
UPDATE IGNORE `bbtaxtype` SET `taxType` = '8752 Required Payment or Refund Under Section 7519' WHERE (`id` = '38');
UPDATE IGNORE `bbtaxtype` SET `taxType` = '8804 Annual Return for Partnership Withholding Tax  (Section 1446)' WHERE (`id` = '39');
UPDATE IGNORE `bbtaxtype` SET `taxType` = '8805 Foreign Partners Information Statement of Section 1446 Withholding Tax               ' WHERE (`id` = '40');
UPDATE IGNORE `bbtaxtype` SET `taxType` = '8813 Partnership Withholding Tax Payment Voucher  (Section 1446)' WHERE (`id` = '41');
UPDATE IGNORE `bbtaxtype` SET `taxType` = '8831 Excise Taxes on Excess Inclusions of REMIC  Residual Interests ' WHERE (`id` = '42');
UPDATE IGNORE `bbtaxtype` SET `taxType` = '8876 Excise Tax on Structured Settlement Factoring Payment due with a return 88761 Transactions           ' WHERE (`id` = '43');
UPDATE IGNORE `bbtaxtype` SET `taxType` = 'CT-1 - Employer’s Annual Railroad Retirement Tax Return' WHERE (`id` = '44');
UPDATE IGNORE `bbtaxtype` SET `taxType` = '8038 Information Return for Tax Exempt Private Activity Bond-Issues' WHERE (`id` = '45');
UPDATE IGNORE `bbtaxtype` SET `taxType` = '8963 - Insurance Provider Fee ' WHERE (`id` = '46');

INSERT INTO `systemconfiguration` (`id`, `PropertyName`, `PropertyValue`, `createdts`, `lastmodifiedts`, `synctimestamp`) VALUES ('12', 'DBP_API_ACCESS_TOKEN', 'CXh_j9yYh7gHP4cJb9RbZloxgj8SB21Z7lTqTNCl3A8', '2019-06-04 06:05:00', '2019-06-04 06:05:00', '2019-06-04 06:05:00');