UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Self Employed' WHERE `id`='PA_BUSINESSSTARTDATE';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Self Employed' WHERE `id`='PA_COAPPBUSINESSSTARTDATE';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Self Employed' WHERE `id`='PA_COAPPINCOMEBUSINESSADDRESSCITY';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Self Employed' WHERE `id`='PA_COAPPINCOMEBUSINESSADDRESSCOUNTRY';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Self Employed' WHERE `id`='PA_COAPPINCOMEBUSINESSADDRESSLINE1';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Self Employed' WHERE `id`='PA_COAPPINCOMEBUSINESSADDRESSLINE2';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Self Employed' WHERE `id`='PA_COAPPINCOMEBUSINESSADDRESSSTATE';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Self Employed' WHERE `id`='PA_COAPPINCOMEBUSINESSADDRESSZIPCODE';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Self Employed' WHERE `id`='PA_COAPPINCOMEBUSINESSNAME';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Self Employed' WHERE `id`='PA_INCOMEBUSINESSADDRESSCITY';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Self Employed' WHERE `id`='PA_INCOMEBUSINESSADDRESSCOUNTRY';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Self Employed' WHERE `id`='PA_INCOMEBUSINESSADDRESSLINE1';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Self Employed' WHERE `id`='PA_INCOMEBUSINESSADDRESSLINE2';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Self Employed' WHERE `id`='PA_INCOMEBUSINESSADDRESSSTATE';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Self Employed' WHERE `id`='PA_INCOMEBUSINESSADDRESSZIPCODE';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Self Employed' WHERE `id`='PA_INCOMEBUSINESSNAME';
REPLACE INTO `loansconfigurations` (`bundle_id`, `config_type`, `config_key`, `config_value`, `description`, `lastUpdatedTime`) VALUES ('10', 'PREFERENCE', 'VEHICLE_MAX_LOAN_TERMS', '120', 'LoanTerms', '2018-11-16 13:48:43.000000');
REPLACE INTO `loansconfigurations` (`bundle_id`, `config_type`, `config_key`, `config_value`, `description`, `lastUpdatedTime`) VALUES ('11', 'PREFERENCE', 'VEHICLE_DEFAULT_LOAN_AMOUNT', '15000', 'Default LoanAmount', '2018-11-16 13:48:43.000000');
REPLACE INTO `loansconfigurations` (`bundle_id`, `config_type`, `config_key`, `config_value`, `description`, `lastUpdatedTime`) VALUES ('12', 'PREFERENCE', 'PERSONAL_LOANTERMS_MAX', '120', 'LoanTerms', '2018-11-16 13:48:43.000000');
REPLACE INTO `loansconfigurations` (`bundle_id`, `config_type`, `config_key`, `config_value`, `description`, `lastUpdatedTime`) VALUES ('13', 'PREFERENCE', 'PERSONAL_LOANTERMS_MIN', '12', 'LoanTerms', '2018-11-16 13:48:43.000000');
REPLACE INTO `loansconfigurations` (`bundle_id`, `config_type`, `config_key`, `config_value`, `description`, `lastUpdatedTime`) VALUES ('14', 'PREFERENCE', 'VEHICLE_DEFAULT_LOAN_TERMS_STEP', '2', 'LoanTermsStep', '2018-11-16 13:48:43.000000');
REPLACE INTO `loansconfigurations` (`bundle_id`, `config_type`, `config_key`, `config_value`, `description`, `lastUpdatedTime`) VALUES ('15', 'PREFERENCE', 'VEHICLE_DEFAULT_LOAN_TERMS', '42', 'DefaultLoanTerms', '2018-11-16 13:48:43.000000');
REPLACE INTO `loansconfigurations` (`bundle_id`, `config_type`, `config_key`, `config_value`, `description`, `lastUpdatedTime`) VALUES ('16', 'PREFERENCE', 'VEHICLE_LOAN_AMOUNT_STEP', '100', 'LoanAmountStep', '2018-11-16 13:48:43.000000');
REPLACE INTO `loansconfigurations` (`bundle_id`, `config_type`, `config_key`, `config_value`, `description`, `lastUpdatedTime`) VALUES ('17', 'PREFERENCE', 'PERSONAL_LOAN_AMOUNT_STEP', '100', 'LoanAmountStep', '2018-11-16 13:48:43.000000');
REPLACE INTO `loansconfigurations` (`bundle_id`, `config_type`, `config_key`, `config_value`, `description`, `lastUpdatedTime`) VALUES ('18', 'PREFERENCE', 'PERSONAL_DEFAULT_LOAN_AMOUNT', '15000', 'Default LoanAmount', '2018-11-16 13:48:43.000000');
REPLACE INTO `loansconfigurations` (`bundle_id`, `config_type`, `config_key`, `config_value`, `description`, `lastUpdatedTime`) VALUES ('19', 'PREFERENCE', 'PERSONAL_DEFAULT_LOAN_TERMS', '42', 'LoanTerms', '2018-11-16 13:48:43.000000');
REPLACE INTO `loansconfigurations` (`bundle_id`, `config_type`, `config_key`, `config_value`, `description`, `lastUpdatedTime`) VALUES ('20', 'PREFERENCE', 'PERSONAL_DEFAULT_LOAN_TERMS_STEP', '2', 'LoanTermsStep', '2018-11-16 13:48:43.000000');
REPLACE INTO `loansconfigurations` (`bundle_id`, `config_type`, `config_key`, `config_value`, `description`, `lastUpdatedTime`) VALUES ('21', 'SERVER', 'LINK_EXPIRY_TIME', '1', 'ExpiryTime', '2018-11-16 13:48:43.000000');
REPLACE INTO `loansconfigurations` (`bundle_id`, `config_type`, `config_key`, `config_value`, `description`, `lastUpdatedTime`) VALUES ('7', 'PREFERENCE', 'VEHICLE_MAX_LOAN_AMOUNT', '30000', 'LoanAmount', '2018-11-16 13:48:43.000000');
REPLACE INTO `loansconfigurations` (`bundle_id`, `config_type`, `config_key`, `config_value`, `description`, `lastUpdatedTime`) VALUES ('8', 'PREFERENCE', 'VEHICLE_MIN_LOAN_AMOUNT', '1000', 'LoanAmount', '2018-11-16 13:48:43.000000');
REPLACE INTO `loansconfigurations` (`bundle_id`, `config_type`, `config_key`, `config_value`, `description`, `lastUpdatedTime`) VALUES ('9', 'PREFERENCE', 'VEHICLE_MIN_LOAN_TERMS', '12', 'LoanTerms', '2018-11-16 13:48:43.000000');
REPLACE INTO `loansconfigurationmasters` (`bundle_id`, `app_id`, `channels`, `user_id`, `role`) VALUES ('10', 'ConsumerLending', 'thinclient', 'null', 'basc');
REPLACE INTO `loansconfigurationmasters` (`bundle_id`, `app_id`, `channels`, `user_id`, `role`) VALUES ('11', 'ConsumerLending', 'thinclient', 'null', 'basic');
REPLACE INTO `loansconfigurationmasters` (`bundle_id`, `app_id`, `channels`, `user_id`, `role`) VALUES ('12', 'ConsumerLending', 'thinclient', 'null', 'basic');
REPLACE INTO `loansconfigurationmasters` (`bundle_id`, `app_id`, `channels`, `user_id`, `role`) VALUES ('13', 'ConsumerLending', 'thinclient', 'null', 'basic');
REPLACE INTO `loansconfigurationmasters` (`bundle_id`, `app_id`, `channels`, `user_id`, `role`) VALUES ('14', 'ConsumerLending', 'thinclient', 'null', 'basic');
REPLACE INTO `loansconfigurationmasters` (`bundle_id`, `app_id`, `channels`, `user_id`, `role`) VALUES ('15', 'ConsumerLending', 'thinclient', 'null', 'basic');
REPLACE INTO `loansconfigurationmasters` (`bundle_id`, `app_id`, `channels`, `user_id`, `role`) VALUES ('16', 'ConsumerLending', 'thinclient', 'null', 'basic');
REPLACE INTO `loansconfigurationmasters` (`bundle_id`, `app_id`, `channels`, `user_id`, `role`) VALUES ('17', 'ConsumerLending', 'thinclient', 'null', 'basic');
REPLACE INTO `loansconfigurationmasters` (`bundle_id`, `app_id`, `channels`, `user_id`, `role`) VALUES ('18', 'ConsumerLending', 'thinclient', 'null', 'basic');
REPLACE INTO `loansconfigurationmasters` (`bundle_id`, `app_id`, `channels`, `user_id`, `role`) VALUES ('19', 'ConsumerLending', 'thinclient', 'null', 'basic');
REPLACE INTO `loansconfigurationmasters` (`bundle_id`, `app_id`, `channels`, `user_id`, `role`) VALUES ('20', 'ConsumerLending', 'thinclient', 'null', ' basic');
REPLACE INTO `loansconfigurationmasters` (`bundle_id`, `app_id`, `channels`, `user_id`, `role`) VALUES ('7', 'ConsumerLending', 'thinclient', 'null', 'basic');
REPLACE INTO `loansconfigurationmasters` (`bundle_id`, `app_id`, `channels`, `user_id`, `role`) VALUES ('8', 'ConsumerLending', 'thinclient', 'null', 'basic');
REPLACE INTO `loansconfigurationmasters` (`bundle_id`, `app_id`, `channels`, `user_id`, `role`) VALUES ('9', 'ConsumerLending', 'thinclient', 'null', 'basic');
UPDATE `querysectionquestion` SET `abstractName`='AddIncomeALIMONY' WHERE `id`='PA_ADDINCOME_ALIMONY';
UPDATE `questiondefinition` SET `OptionGroup_id`='PAY_PERIOD_TYPE_SELECT' WHERE `id`='PERSONAL_ADD_INCOME_OTHER';
UPDATE `questiondefinition` SET `OptionGroup_id`='PAY_PERIOD_TYPE_SELECT' WHERE `id`='PERSONAL_COAPP_ADD_INCOME_OTHER';
UPDATE `loansconfigurations` SET `config_value`='1000' WHERE `bundle_id`='17';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppEmploymentStatus' WHERE `id`='VA_COAPP_BUSINESS_NAME';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppEmploymentStatus' WHERE `id`='VA_COAPP_BUSINESS_START_DATE';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppEmploymentStatus' WHERE `id`='VA_COAPP_CURR_EMPLOYER';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppEmploymentStatus' WHERE `id`='VA_COAPP_DESIGNATION';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppEmploymentStatus' WHERE `id`='VA_COAPP_EMP_ADDLINE2';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppEmploymentStatus' WHERE `id`='VA_COAPP_PREVIOUS_EMPLOYER_CHAL';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppEmploymentStatus' WHERE `id`='VA_COAPP_START_DATE_EMPLOYER';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppEmploymentStatus' WHERE `id`='VEHICLE_COAPPLICANT_EMP_CITY';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppEmploymentStatus' WHERE `id`='VEHICLE_COAPPLICANT_EMP_COUNTRY';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppEmploymentStatus' WHERE `id`='VEHICLE_COAPPLICANT_EMP_STATE';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppEmploymentStatus' WHERE `id`='VEHICLE_COAPPLICANT_EMP_ZIPCODE';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppEmploymentStatus' WHERE `id`='VEHICLE_CoApp_BUSINESS_ADDLINE1+';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppEmploymentStatus' WHERE `id`='VEHICLE_CoApp_BUSINESS_ADDLINE2';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppEmploymentStatus' WHERE `id`='VEHICLE_CoApp_BUSINESS_CITY';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppEmploymentStatus' WHERE `id`='VEHICLE_CoApp_BUSINESS_COUNTRY';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppEmploymentStatus' WHERE `id`='VEHICLE_CoApp_BUSINESS_STATE';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppEmploymentStatus' WHERE `id`='VEHICLE_CoApp_EMP_ADDLINE1_PT';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppEmploymentStatus' WHERE `id`='VEHICLE_CoApp_BUSINESS_ZIPCODE';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppEmploymentStatus' WHERE `id`='VEHICLE_CoApp_EMP_ADDLINE2_PT';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppEmploymentStatus' WHERE `id`='VEHICLE_CoApp_EMP_CITY_PT';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppEmploymentStatus' WHERE `id`='VEHICLE_CoApp_EMP_COUNTRY_PT';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppEmploymentStatus' WHERE `id`='VEHICLE_CoApp_EMP_STATE_PT';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppEmploymentStatus' WHERE `id`='VEHICLE_CoApp_EMP_ZIPCODE_PT';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppEmploymentStatus' WHERE `id`='﻿VEHICLE_COAPPLICANT_EMP_ADDLINE1';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppPrevEmployerChallenge' WHERE `id`='VA_COAPP_PREVIOUS_EMPLOYER';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppPrevEmployerChallenge' WHERE `id`='VEHICLE_COAPPLICANT_PREVEMP_ADDLINE2';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppPrevEmployerChallenge' WHERE `id`='VEHICLE_COAPPLICANT_PREVEMP_CITY';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppPrevEmployerChallenge' WHERE `id`='VEHICLE_COAPPLICANT_PREVEMP_COUNTRY';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppPrevEmployerChallenge' WHERE `id`='VEHICLE_COAPPLICANT_PREVEMP_STATE';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppPrevEmployerChallenge' WHERE `id`='VEHICLE_COAPPLICANT_PREVEMP_ZIPCODE';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppPrevEmployerChallenge' WHERE `id`='﻿VEHICLE_COAPPLICANT_PREVEMP_ADDLINE1';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppPrevEmployerChallenge' WHERE `id`='﻿VEHICLE_CoApp_PREVEMP_DESIGNATION';
REPLACE INTO `questiondefinition` (`id`, `QueryDefinition_id`, `IsRequired`, `createdts`, `lastmodifiedts`, `synctimestamp`, `softdeleteflag`) VALUES ('CREDIT_CARD_ADD_INCOME_OTHER_NAME', 'CREDIT_CARD_APPLICATION', '1', '2018-11-09 15:39:52', '2018-11-09 15:39:52', '2018-11-09 15:39:52', '0');
REPLACE INTO `querysectionquestion` (`id`, `QueryDefinition_id`, `QuerySection_id`, `QuestionDefinition_id`, `Sequence`, `IsRequired`, `createdts`, `lastmodifiedts`, `synctimestamp`, `softdeleteflag`, `abstractName`) VALUES ('CCA_ADDINCOME_OTHERNAME', 'CREDIT_CARD_APPLICATION', 'CREDIT_CARD_INCOME_APPLICANT', 'CREDIT_CARD_ADD_INCOME_OTHER_NAME', '0', '1', '2018-11-11 05:57:56', '2018-11-11 05:57:56', '2018-11-11 05:57:56', '0', 'AddIncomeOtherName');
REPLACE INTO `questiondefinition` (`id`, `QueryDefinition_id`, `IsRequired`, `createdts`, `lastmodifiedts`, `synctimestamp`, `softdeleteflag`) VALUES ('VA_ADD_INCOME_OTHER_NAME', 'VEHICLE_APPLICATION', '1', '2018-11-09 15:39:52', '2018-11-09 15:39:52', '2018-11-09 15:39:52', '0');
REPLACE INTO `questiondefinition` (`id`, `QueryDefinition_id`, `IsRequired`, `createdts`, `lastmodifiedts`, `synctimestamp`, `softdeleteflag`) VALUES ('VA_COAPP_ADD_INCOME_OTHER_NAME', 'VEHICLE_APPLICATION', '1', '2018-11-09 15:39:52', '2018-11-09 15:39:52', '2018-11-09 15:39:52', '0');
REPLACE INTO `querysectionquestion` (`id`, `QueryDefinition_id`, `QuerySection_id`, `QuestionDefinition_id`, `Sequence`, `IsRequired`, `createdts`, `lastmodifiedts`, `synctimestamp`, `softdeleteflag`, `abstractName`) VALUES ('VA_ADDINCOME_OTHERNAME', 'VEHICLE_APPLICATION', 'VEHICLE_APPLICATION_INCOME_APPLICANT', 'VA_ADD_INCOME_OTHER_NAME', '0', '1', '2018-11-11 05:57:56', '2018-11-11 05:57:56', '2018-11-11 05:57:56', '0', 'AddIncomeOtherName');
REPLACE INTO `querysectionquestion` (`id`, `QueryDefinition_id`, `QuerySection_id`, `QuestionDefinition_id`, `Sequence`, `IsRequired`, `createdts`, `lastmodifiedts`, `synctimestamp`, `softdeleteflag`, `abstractName`) VALUES ('VA_COAPP_ADDINCOME_OTHERNAME', 'VEHICLE_APPLICATION', 'VEHICLE_APPLICATION_INCOME_COAPPLICANT', 'VA_COAPP_ADD_INCOME_OTHER_NAME', '0', '1', '2018-11-11 05:57:56', '2018-11-11 05:57:56', '2018-11-11 05:57:56', '0', 'CoAppAddIncomeOtherName');
REPLACE INTO `questiondefinition` (`id`, `QueryDefinition_id`, `IsRequired`, `createdts`, `lastmodifiedts`, `synctimestamp`, `softdeleteflag`) VALUES ('PA_ADD_INCOME_OTHER_NAME', 'PERSONAL_APPLICATION', '1', '2018-11-09 15:39:52', '2018-11-09 15:39:52', '2018-11-09 15:39:52', '0');
REPLACE INTO `questiondefinition` (`id`, `QueryDefinition_id`, `IsRequired`, `createdts`, `lastmodifiedts`, `synctimestamp`, `softdeleteflag`) VALUES ('PA_COAPP_ADD_INCOME_OTHER_NAME', 'PERSONAL_APPLICATION', '1', '2018-11-09 15:39:52', '2018-11-09 15:39:52', '2018-11-09 15:39:52', '0');
REPLACE INTO `querysectionquestion` (`id`, `QueryDefinition_id`, `QuerySection_id`, `QuestionDefinition_id`, `Sequence`, `IsRequired`, `createdts`, `lastmodifiedts`, `synctimestamp`, `softdeleteflag`, `abstractName`) VALUES ('PA_ADDINCOME_OTHERNAME', 'PERSONAL_APPLICATION', 'PERSONAL_INCOME_APPLICANT', 'PA_ADD_INCOME_OTHER_NAME', '0', '1', '2018-11-11 05:57:56', '2018-11-11 05:57:56', '2018-11-11 05:57:56', '0', 'AddIncomeOtherName');
REPLACE INTO `querysectionquestion` (`id`, `QueryDefinition_id`, `QuerySection_id`, `QuestionDefinition_id`, `Sequence`, `IsRequired`, `createdts`, `lastmodifiedts`, `synctimestamp`, `softdeleteflag`, `abstractName`) VALUES ('PA_COAPP_ADDINCOME_OTHERNAME', 'PERSONAL_APPLICATION', 'PERSONAL_INCOME_COAPPLICANT', 'PA_COAPP_ADD_INCOME_OTHER_NAME', '0', '1', '2018-11-11 05:57:56', '2018-11-11 05:57:56', '2018-11-11 05:57:56', '0', 'CoAppAddIncomeOtherName');
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='HavntFoundVehicle', `ParentQuestionOptionValue`='No' WHERE `id`='VA_VEHICLE_TYPE';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='HavntFoundVehicle', `ParentQuestionOptionValue`='No' WHERE `id`='VA_VEHICLE_MAKE_YEAR';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='HavntFoundVehicle', `ParentQuestionOptionValue`='No' WHERE `id`='VA_VEHICLE_MODEL';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='HavntFoundVehicle', `ParentQuestionOptionValue`='No' WHERE `id`='VA_VEHICLE_MAKER';
UPDATE `loantype` SET `APRValue`='8.49' WHERE `id`='CREDIT_CARD';
UPDATE `loantype` SET `APRValue`='4.64' WHERE `id`='VEHICLE_LOAN';
UPDATE `loantype` SET `APRValue`='9.49' WHERE `id`='PERSONAL_LOAN';
UPDATE `loantype` SET `APRValue`='7.75' WHERE `id`='MORTGAGE_LOAN';
UPDATE `loanproduct` SET `APR`='8.49' WHERE `id`='JUMBO_CREDIT_CARD';
UPDATE `loanproduct` SET `APR`='8.49' WHERE `id`='MICRO_CREDIT_CARD';
UPDATE `loanproduct` SET `APR`='8.49' WHERE `id`='MINI_CREDIT_CARD';
UPDATE `loanproduct` SET `APR`='8.49' WHERE `id`='SPECIAL_CREDIT_CARD';
UPDATE `loanproduct` SET `APR`='4.64' WHERE `id`='JUMBO_VEHICLE_LOAN';
UPDATE `loanproduct` SET `APR`='9.49' WHERE `id`='JUMBO_PERSONAL_LOAN';
REPLACE INTO `loansconfigurations` (`bundle_id`, `config_type`, `config_key`, `config_value`, `description`, `lastUpdatedTime`) VALUES ('22', 'PREFERENCE', 'CREDIT_CARD_FORM_SEQUENCE_CONFIG', '[\"frmVerifyCreditCard\",\"frmApplicantInfoCKA\",\"frmApplicantIncomeKA\",\"frmAuthUserInfoKA\",\"frmTermsAndConditions\"]', 'Sequence Config for CC Application', '2018-11-16 13:48:43.000000');
REPLACE INTO `loansconfigurationmasters` (`bundle_id`, `app_id`, `channels`, `user_id`, `role`) VALUES ('22', 'ConsumerLending', 'thinclient', 'null', 'basic');
REPLACE INTO `loansconfigurations` (`bundle_id`, `config_type`, `config_key`, `config_value`, `description`, `lastUpdatedTime`) VALUES ('23', 'PREFERENCE', 'CREDIT_CARD_DEPENDENT_FORM_SEQUENCE_CONFIG', '[\"frmAuthUserInfoKA\"]', 'Dependent Sequence Config for CC Application', '2018-11-16 13:48:43.000000');
REPLACE INTO `loansconfigurationmasters` (`bundle_id`, `app_id`, `channels`, `user_id`, `role`) VALUES ('23', 'ConsumerLending', 'thinclient', 'null', 'basic');
REPLACE INTO `loansconfigurations` (`bundle_id`, `config_type`, `config_key`, `config_value`, `description`, `lastUpdatedTime`) VALUES ('24', 'PREFERENCE', 'CREDIT_CARD_FORM_SECTION_CONFIG', '{\"frmVerifyCreditCard\":[\"CardInfo\"],\"frmApplicantInfoCKA\":[\"PersonalInfo\"],\"frmApplicantIncomeKA\":[\"Income\"],\"frmAuthUserInfoKA\":[\"AUPersonalInfo\"],\"frmTermsAndConditions\":[\"Consent\"]}', 'Form to section config for CC Application', '2018-11-16 13:48:43.000000');
REPLACE INTO `loansconfigurationmasters` (`bundle_id`, `app_id`, `channels`, `user_id`, `role`) VALUES ('24', 'ConsumerLending', 'thinclient', 'null', 'basic');
REPLACE INTO `loansconfigurations` (`bundle_id`, `config_type`, `config_key`, `config_value`, `description`, `lastUpdatedTime`) VALUES ('25', 'PREFERENCE', 'VEHICLE_APPLICATION_FORM_SEQUENCE_CONFIG', '[\"frmYourVehicleLoanKA\",\"frmApplicantInfoVehicleKA\",\"frmApplicantIncomeVehicleKA\",\"frmCoAppInfoVehicleKA\",\"frmCoApplicantIncomeVehicleKA\",\"frmConsentVehicleKA\"]', 'Sequence Config for VA Application', '2018-11-16 13:48:43.000000');
REPLACE INTO `loansconfigurations` (`bundle_id`, `config_type`, `config_key`, `config_value`, `description`, `lastUpdatedTime`) VALUES ('26', 'PREFERENCE', 'VEHICLE_APPLICATION_FORM_SECTION_CONFIG', '{\"frmYourVehicleLoanKA\" : [\"VehicleLoan\", \"CAFlags\"],\"frmApplicantInfoVehicleKA\" : [\"PersonalInfo\"],\"frmApplicantIncomeVehicleKA\" : [\"Income\"],\"frmCoAppInfoVehicleKA\" : [\"CoAppPersonalInfo\", \"CAFlags\"],\"frmCoApplicantIncomeVehicleKA\" : [\"CoAppIncome\"],\"frmConsentVehicleKA\": [\"Consent\"]}', 'Form to section config for VA Application', '2018-11-16 13:48:43.000000');
REPLACE INTO `loansconfigurations` (`bundle_id`, `config_type`, `config_key`, `config_value`, `description`, `lastUpdatedTime`) VALUES ('27', 'PREFERENCE', 'VEHICLE_APPLICATION_DEPENDENT_FORM_SEQUENCE_CONFIG', '[\"frmCoAppInfoVehicleKA\",\"frmCoApplicantIncomeVehicleKA\"]', 'Dependent Sequence Config for VA Application', '2018-11-16 13:48:43.000000');
REPLACE INTO `loansconfigurationmasters` (`bundle_id`, `app_id`, `channels`, `user_id`, `role`) VALUES ('25', 'ConsumerLending', 'thinclient', 'null', 'basic'); 
REPLACE INTO `loansconfigurationmasters` (`bundle_id`, `app_id`, `channels`, `user_id`, `role`) VALUES ('26', 'ConsumerLending', 'thinclient', 'null', 'basic');
REPLACE INTO `loansconfigurationmasters` (`bundle_id`, `app_id`, `channels`, `user_id`, `role`) VALUES ('27', 'ConsumerLending', 'thinclient', 'null', 'basic');
REPLACE INTO `loansconfigurations` (`bundle_id`, `config_type`, `config_key`, `config_value`, `description`) VALUES ('28', 'PREFERENCE', 'PERSONAL_APPLICATION_FORM_SEQUENCE_CONFIG', '[\"frmYourLoanNewKA\",\"frmApplicantInfoKA\",\"frmEmploymentInfoKA\",\"frmCoApplicantInfoKA\",\"frmCoApplicantEmploymentInfoKA\",\"frmConsentKA\"]', 'Sequence Config for PA Application'); 
REPLACE INTO `loansconfigurations` (`bundle_id`, `config_type`, `config_key`, `config_value`, `description`) VALUES ('29', 'PREFERENCE', 'PERSONAL_APPLICATION_FORM_SECTION_CONFIG', '{\"frmYourLoanNewKA\" : [\"YourLoan\", \"CAFlags\"],\"frmApplicantInfoKA\" : [\"PersonalInfo\"],\"frmEmploymentInfoKA\" : [\"Income\"],\"frmCoApplicantInfoKA\" : [\"CoAppPersonalInfo\", \"CAFlags\"],\"frmCoApplicantEmploymentInfoKA\" : [\"CoAppIncome\"],\"frmConsentKA\":[\"Consent\"]}', 'Form to section config for PA Application'); 
REPLACE INTO `loansconfigurations` (`bundle_id`, `config_type`, `config_key`, `config_value`, `description`) VALUES ('30', 'PREFERENCE', 'PERSONAL_APPLICATION_DEPENDENT_FORM_SEQUENCE_CONFIG', '[\"frmCoApplicantInfoKA\",\"frmCoApplicantEmploymentInfoKA\"]', 'Dependent Sequence Config for PA Application'); 
REPLACE INTO `loansconfigurationmasters` (`bundle_id`, `app_id`, `channels`, `user_id`, `role`) VALUES ('28', 'ConsumerLending', 'thinclient', 'null', 'basic');
REPLACE INTO `loansconfigurationmasters` (`bundle_id`, `app_id`, `channels`, `user_id`, `role`) VALUES ('29', 'ConsumerLending', 'thinclient', 'null', 'basic'); 
REPLACE INTO `loansconfigurationmasters` (`bundle_id`, `app_id`, `channels`, `user_id`, `role`) VALUES ('30', 'ConsumerLending', 'thinclient', 'null', 'basic');
DELETE FROM `querysectionquestion` WHERE (`id` = 'CCA_AUCURDURATION');
DELETE FROM `querysectionquestion` WHERE (`id` = 'CCA_AUHOMETYPE');
DELETE FROM `querysectionquestion` WHERE (`id` = 'CCA_PREVADDTYPE');
REPLACE INTO `questiondefinition` (`id`, `QueryDefinition_id`, `DataType_id`, `OptionGroup_id`, `Unit`, `Name`, `Label`, `OtherLabel`, `IsRequired`, `createdby`, `modifiedby`, `createdts`, `lastmodifiedts`, `synctimestamp`, `softdeleteflag`) VALUES ('CREDIT_CARD_SCAN_DOCUMENT', 'CREDIT_CARD_APPLICATION', 'temp', 'DOCUMENT_SCAN_OPTIONS', 'NULL', '', '', '', '1', 'NULL', 'NULL', CURRENT_TIMESTAMP, '2018-11-13 10:32:27', '2018-11-13 10:32:27', '0');
REPLACE INTO `querysectionquestion` (`id`, `QueryDefinition_id`, `QuerySection_id`, `QuestionDefinition_id`, `Sequence`, `IsRequired`, `createdby`, `modifiedby`, `createdts`, `lastmodifiedts`, `synctimestamp`, `softdeleteflag`, `abstractName`) VALUES ('CCA_SCAN_DOCUMENT', 'CREDIT_CARD_APPLICATION', 'CREDIT_CARD_PERSONAL_INFO_APPLICANT', 'CREDIT_CARD_SCAN_DOCUMENT', '0', '1', '', '', '2018-08-06 09:25:00', '2018-11-06 08:20:50', '2018-11-06 08:20:50', '0', 'ScanDocument');
REPLACE INTO `questiondefinition` (`id`, `QueryDefinition_id`, `DataType_id`, `Unit`, `Name`, `Label`, `OtherLabel`, `IsRequired`, `createdby`, `modifiedby`, `createdts`, `lastmodifiedts`, `synctimestamp`, `softdeleteflag`) VALUES ('CREDIT_CARD_EMPLOYER_START_DATE_OTHER', 'CREDIT_CARD_APPLICATION', '', '', '', '', '', '1', '', '', '2013-07-17 11:48:00', '2013-07-17 11:48:00', '2013-07-17 11:48:00', '0');
REPLACE INTO `querysectionquestion` (`id`, `QueryDefinition_id`, `QuerySection_id`, `QuestionDefinition_id`, `ParentQuestionOptionValue`, `Sequence`, `IsRequired`, `createdby`, `createdts`, `lastmodifiedts`, `synctimestamp`, `softdeleteflag`, `abstractName`, `ParentQuerySectionQuestion_AbstractName`) VALUES ('CCA_STARTDATE_OTHER', 'CREDIT_CARD_APPLICATION', 'CREDIT_CARD_INCOME_APPLICANT', 'CREDIT_CARD_EMPLOYER_START_DATE_OTHER', 'Other', '0', '1', '', '2018-11-08 10:46:32', '2018-12-27 14:52:15', '2018-12-27 14:52:15', '0', 'OtherIncomeStartDate', 'EmploymentStatus');
UPDATE `loansconfigurations` SET `config_value`='50000' WHERE `bundle_id`='1';
UPDATE `loansconfigurations` SET `config_value`='3000' WHERE `bundle_id`='2';
UPDATE `loansconfigurations` SET `config_value`='[\n  \"Vehicle\",\n  \"Recreational Vehicle\",\n  \"Motorcycle\",\n  \"Water Craft\",\n  \"Farm Equipment\"\n]' WHERE `bundle_id`='3';
UPDATE `loansconfigurations` SET `config_value`='15' WHERE `bundle_id`='4';
UPDATE `loansconfigurations` SET `config_value`='[\n  {\n    \"LoanType_id\": \"CREDIT_CARD\",\n    \"APRValue\": \"20\",\n    \"LoanProduct\": [\n      {\n        \"LoanProduct_id\": \"JUMBO_CREDIT_CARD\",\n        \"JUMBO_CREDIT_CARD\": \"12\",\n        \"APR\": \"11\",\n        \"LoanType_id\": \"CREDIT_CARD\"\n      },\n      {\n        \"LoanProduct_id\": \"MICRO_CREDIT_CARD\",\n        \"APR\": \"12\",\n        \"LoanType_id\": \"CREDIT_CARD\"\n      },\n      {\n        \"LoanProduct_id\": \"MINI_CREDIT_CARD\",\n        \"APR\": \"12\",\n        \"LoanType_id\": \"CREDIT_CARD\"\n      },\n      {\n        \"LoanProduct_id\": \"SPECIAL_CREDIT_CARD\",\n        \"APR\": \"12\",\n        \"LoanType_id\": \"CREDIT_CARD\"\n      }\n    ]\n  },\n  {\n    \"LoanType_id\": \"MORTGAGE_LOAN\",\n    \"APRValue\": \"25\",\n    \"LoanProduct\": [\n      {\n        \"LoanProduct_id\": \"HOME_MORTGAGE\",\n        \"APR\": \"11\",\n        \"LoanType_id\": \"MORTGAGE_LOAN\"\n      }\n    ]\n  },\n  {\n    \"LoanType_id\": \"PERSONAL_LOAN\",\n    \"APRValue\": \"30\",\n    \"LoanProduct\": [\n      {\n        \"LoanProduct_id\": \"JUMBO_PERSONAL_LOAN\",\n        \"APR\": \"12\",\n        \"LoanType_id\": \"PERSONAL_LOAN\"\n      }\n    ]\n  },\n  {\n    \"LoanType_id\": \"VEHICLE_LOAN\",\n    \"APRValue\": \"35\",\n    \"LoanProduct\": [\n      {\n        \"LoanProduct_id\": \"JUMBO_VEHICLE_LOAN\",\n        \"APR\": \"12\",\n        \"LoanType_id\": \"VEHICLE_LOAN\"\n      }\n    ]\n  }\n]' WHERE `bundle_id`='5';
UPDATE `loansconfigurations` SET `config_value`='[\n  {\n    \"CreditScore\": \"Excellent (720 or Above)\",\n    \"LoanAmount\": \"15000\"\n  },\n  {\n    \"CreditScore\": \"Excellent (720 or Above)\",\n    \"LoanAmount\": \"35000\",\n    \"VehicleModelYear\": \"2019\",\n    \"VehicleType\": \"Vehicle\",\n    \"LoanPurpose\": \"Purchase a new vehicle\"\n  }\n]' WHERE `bundle_id`='6';
UPDATE `loansconfigurations` SET `config_value`='50000' WHERE `bundle_id`='7';
UPDATE `loansconfigurations` SET `config_value`='1000' WHERE `bundle_id`='8';
UPDATE `loansconfigurations` SET `config_value`='12' WHERE `bundle_id`='9';
UPDATE `loansconfigurations` SET `config_value`='200' WHERE `bundle_id`='10';
UPDATE `loansconfigurations` SET `config_value`='15000' WHERE `bundle_id`='11';
UPDATE `loansconfigurations` SET `config_value`='120' WHERE `bundle_id`='12';
UPDATE `loansconfigurations` SET `config_value`='12' WHERE `bundle_id`='13';
UPDATE `loansconfigurations` SET `config_value`='2' WHERE `bundle_id`='14';
UPDATE `loansconfigurations` SET `config_value`='42' WHERE `bundle_id`='15';
UPDATE `loansconfigurations` SET `config_value`='100' WHERE `bundle_id`='16';
UPDATE `loansconfigurations` SET `config_value`='1000' WHERE `bundle_id`='17';
UPDATE `loansconfigurations` SET `config_value`='15000' WHERE `bundle_id`='18';
UPDATE `loansconfigurations` SET `config_value`='42' WHERE `bundle_id`='19';
UPDATE `loansconfigurations` SET `config_value`='2' WHERE `bundle_id`='20';
UPDATE `loansconfigurations` SET `config_value`='1' WHERE `bundle_id`='21';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppEmploymentStatus' WHERE `id`='VA_COAPP_INCOME_BUSINESS_INCOME';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppEmploymentStatus' WHERE `id`='VEHICLE_COAPP_OTHER_EMPLOYMENTTYPE_DESCRPTION';
REPLACE INTO `loansconfigurations` (`bundle_id`, `config_type`, `config_key`, `config_value`, `description`) VALUES ('31', 'PREFERENCE', 'CREDIT_CARD_MAX_LIMIT', '35000', 'Credit Limit Max');
REPLACE INTO `loansconfigurations` (`bundle_id`, `config_type`, `config_key`, `config_value`, `description`) VALUES ('32', 'PREFERENCE', 'CREDIT_CARD_MIN_LIMIT', '500', 'Credit Limit Min');
REPLACE INTO `loansconfigurations` (`bundle_id`, `config_type`, `config_key`, `config_value`, `description`) VALUES ('33', 'PREFERENCE', 'CREDIT_CARD_LIMIT_STEP', '35000', 'Credit Limit step for slider');
REPLACE INTO `loansconfigurationmasters` (`bundle_id`, `app_id`, `channels`, `user_id`, `role`) VALUES ('31', 'ConsumerLending', 'thinclient', 'null', 'basic');
REPLACE INTO `loansconfigurationmasters` (`bundle_id`, `app_id`, `channels`, `user_id`, `role`) VALUES ('32', 'ConsumerLending', 'thinclient', 'null', 'basic');
REPLACE INTO `loansconfigurationmasters` (`bundle_id`, `app_id`, `channels`, `user_id`, `role`) VALUES ('33', 'ConsumerLending', 'thinclient', 'null', 'basic');
UPDATE `loansconfigurations` SET `config_value` = '1000' WHERE (`bundle_id` = '32');
REPLACE INTO `loansconfigurations` (`bundle_id`, `config_type`, `config_key`, `config_value`, `description`, `lastUpdatedTime`) VALUES ('34', 'PREFERENCE', 'CREDIT_CARD_LIMIT_DEFAULT', '1000', 'Default credit limit', '2018-11-16 13:48:43.000000');
REPLACE INTO `loansconfigurationmasters` (`bundle_id`, `app_id`, `channels`, `user_id`, `role`) VALUES ('34', 'ConsumerLending', 'thinclient', 'null', 'basic');
UPDATE `loansconfigurations` SET `config_value` = '1000' WHERE (`bundle_id` = '33');
UPDATE `loansconfigurations` SET `config_value` = '10000' WHERE (`bundle_id` = '34');
DELETE FROM `querysectionquestion` WHERE `id`='VA_COAPP_PARTTIMEINCOME';
DELETE FROM `querysectionquestion` WHERE `id`='PS_EMPLOYMENTTYPE';
DELETE FROM `querysectionquestion` WHERE `id`='PA_PERSONALINFOCURRADDLINE1';
DELETE FROM `querysectionquestion` WHERE `id`='PA_PERSONALINFOCURRADDLINE2';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppCurrentAddressDuration', `ParentQuestionOptionValue`='Less than two years' WHERE `id`='VA_COAPP_PREV_ADD_CITY';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppCurrentAddressDuration', `ParentQuestionOptionValue`='Less than two years' WHERE `id`='VA_COAPP_PREV_ADD_COUNTRY';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppCurrentAddressDuration', `ParentQuestionOptionValue`='Less than two years' WHERE `id`='VA_COAPP_PREV_ADDLINE1';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppCurrentAddressDuration', `ParentQuestionOptionValue`='Less than two years' WHERE `id`='VA_COAPP_PREV_ADDLINE2';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppCurrentAddressDuration', `ParentQuestionOptionValue`='Less than two years' WHERE `id`='VA_COAPP_PREV_ADD_STATE';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppCurrentAddressDuration', `ParentQuestionOptionValue`='Less than two years' WHERE `id`='VA_COAPP_PREV_ADD_ZIPCODE';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`=NULL, `ParentQuestionOptionValue`=NULL WHERE `id`='VA_COAPP_CURR_ADD_CITY';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`=NULL, `ParentQuestionOptionValue`=NULL WHERE `id`='VA_COAPP_CURR_ADD_COUNTRY';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`=NULL, `ParentQuestionOptionValue`=NULL WHERE `id`='VA_COAPP_CURR_STATE';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`=NULL, `ParentQuestionOptionValue`=NULL WHERE `id`='VA_COAPP_CURR_ADD_ZIPCODE';
UPDATE `loansconfigurations` SET `config_value`='100000' WHERE  `bundle_id`='1';
UPDATE `loansconfigurations` SET `config_value`='100000' WHERE  `bundle_id`='7';
UPDATE `loansconfigurations` SET `config_value`='1000' WHERE  `bundle_id`='2';
UPDATE `loansconfigurations` SET `config_value`='30000' WHERE  `bundle_id`='18';
UPDATE `loansconfigurations` SET `config_value`='[\n  {\n    "CreditScore": "Excellent (720 or Above)",\n    "LoanAmount": "30000"\n  },\n  {\n    "CreditScore": "Excellent (720 or Above)",\n    "LoanAmount": "30000",\n    "VehicleModelYear": "2019",\n    "VehicleType": "Vehicle",\n    "LoanPurpose": "Purchase a new vehicle"\n  }\n]' WHERE  `bundle_id`='6';
UPDATE `loansconfigurations` SET `config_value`='30000' WHERE  `bundle_id`='11';
UPDATE `loansconfigurations` SET `config_value`='1000' WHERE  `bundle_id`='16';
DELETE FROM `optionitem` WHERE `id`='LOAN_PURPOSE_SELECT_9';
UPDATE `optionitem` SET `id`='LOAN_PURPOSE_SELECT_9' WHERE `id`='LOAN_PURPOSE_SELECT_10';
UPDATE `optionitem` SET `DefaultValue`='Social Security' WHERE `id`='INCOME_OTHER_SOURCES_3';