UPDATE `querysectionquestion` SET `ParentQuestionOptionValue` = 'Yes', `ParentQuerySectionQuestion_AbstractName` = 'AddIncomeChallenge' WHERE (`id` = 'CCA_ADDINCOME1');
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue` = 'Yes', `ParentQuerySectionQuestion_AbstractName` = 'AddIncomeChallenge' WHERE (`id` = 'CCA_ADDINCOME2');
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue` = 'Yes', `ParentQuerySectionQuestion_AbstractName` = 'AddIncomeChallenge' WHERE (`id` = 'CCA_ADDINCOME3');
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue` = 'Yes', `ParentQuerySectionQuestion_AbstractName` = 'AddIncomeChallenge' WHERE (`id` = 'CCA_ADDINCOME4');
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue` = 'Yes', `ParentQuerySectionQuestion_AbstractName` = 'AddIncomeChallenge' WHERE (`id` = 'CCA_ADDINCOME5');
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue` = 'Yes', `ParentQuerySectionQuestion_AbstractName` = 'AddIncomeChallenge' WHERE (`id` = 'CCA_ADDINCOME6');
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue` = 'Yes', `ParentQuerySectionQuestion_AbstractName` = 'AddIncomeChallenge' WHERE (`id` = 'CCA_ADDINCOME7');
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue` = 'Yes', `ParentQuerySectionQuestion_AbstractName` = 'AddIncomeChallenge' WHERE (`id` = 'CCA_ADDINCOME_ALIMONY');
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue` = 'Yes', `ParentQuerySectionQuestion_AbstractName` = 'AddIncomeChallenge' WHERE (`id` = 'CCA_ADDINCOME_SOCIALSECURITY');
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue` = 'Yes', `ParentQuerySectionQuestion_AbstractName` = 'AddIncomeChallenge' WHERE (`id` = 'CCA_ADDINCOME_RENTAL');
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue` = 'Yes', `ParentQuerySectionQuestion_AbstractName` = 'AddIncomeChallenge' WHERE (`id` = 'CCA_ADDINCOME_PENSION');
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue` = 'Yes', `ParentQuerySectionQuestion_AbstractName` = 'AddIncomeChallenge' WHERE (`id` = 'CCA_ADDINCOME_OTHERNAME');
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue` = 'Yes', `ParentQuerySectionQuestion_AbstractName` = 'AddIncomeChallenge' WHERE (`id` = 'CCA_ADDINCOME_OTHERDESC');
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue` = 'Yes', `ParentQuerySectionQuestion_AbstractName` = 'AddIncomeChallenge' WHERE (`id` = 'CCA_ADDINCOME_OTHER');
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue` = 'Yes', `ParentQuerySectionQuestion_AbstractName` = 'AddIncomeChallenge' WHERE (`id` = 'CCA_ADDINCOME_INTEREST');
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue` = 'Yes', `ParentQuerySectionQuestion_AbstractName` = 'AddIncomeChallenge' WHERE (`id` = 'CCA_ADDINCOME_ANNUITY');
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='AddIncomeChallenge' WHERE `id`='PA_ADDINCOME1';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='AddIncomeChallenge' WHERE `id`='PA_ADDINCOME2';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='AddIncomeChallenge' WHERE `id`='PA_ADDINCOME3';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='AddIncomeChallenge' WHERE `id`='PA_ADDINCOME4';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='AddIncomeChallenge' WHERE `id`='PA_ADDINCOME5';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='AddIncomeChallenge' WHERE `id`='PA_ADDINCOME6';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='AddIncomeChallenge' WHERE `id`='PA_ADDINCOME7';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='AddIncomeChallenge' WHERE `id`='PA_ADDINCOME_ALIMONY';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='AddIncomeChallenge' WHERE `id`='PA_ADDINCOME_ANNUITY';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='AddIncomeChallenge' WHERE `id`='PA_ADDINCOME_INTEREST';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='AddIncomeChallenge' WHERE `id`='PA_ADDINCOME_OTHER';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='AddIncomeChallenge' WHERE `id`='PA_ADDINCOME_OTHERDESC';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='AddIncomeChallenge' WHERE `id`='PA_ADDINCOME_OTHERNAME';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='AddIncomeChallenge' WHERE `id`='PA_ADDINCOME_PENSION';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='AddIncomeChallenge' WHERE `id`='PA_ADDINCOME_RENTAL';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='AddIncomeChallenge' WHERE `id`='PA_ADDINCOME_SOCIALSECURITY';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppAddIncomeChallenge' WHERE `id`='PA_COAPP_ADDINCOME1';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppAddIncomeChallenge' WHERE `id`='PA_COAPP_ADDINCOME2';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppAddIncomeChallenge' WHERE `id`='PA_COAPP_ADDINCOME3';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppAddIncomeChallenge' WHERE `id`='PA_COAPP_ADDINCOME4';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppAddIncomeChallenge' WHERE `id`='PA_COAPP_ADDINCOME5';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppAddIncomeChallenge' WHERE `id`='PA_COAPP_ADDINCOME6';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppAddIncomeChallenge' WHERE `id`='PA_COAPP_ADDINCOME7';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppAddIncomeChallenge' WHERE `id`='PA_COAPP_ADDINCOME_ALIMONY';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppAddIncomeChallenge' WHERE `id`='PA_COAPP_ADDINCOME_ANNUITY';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppAddIncomeChallenge' WHERE `id`='PA_COAPP_ADDINCOME_INTEREST';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppAddIncomeChallenge' WHERE `id`='PA_COAPP_ADDINCOME_OTHER';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppAddIncomeChallenge' WHERE `id`='PA_COAPP_ADDINCOME_OTHERDESC';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppAddIncomeChallenge' WHERE `id`='PA_COAPP_ADDINCOME_OTHERNAME';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppAddIncomeChallenge' WHERE `id`='PA_COAPP_ADDINCOME_PENSION';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppAddIncomeChallenge' WHERE `id`='PA_COAPP_ADDINCOME_RENTAL';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppAddIncomeChallenge' WHERE `id`='PA_COAPP_ADDINCOME_SOCIALSECURITY';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='AddIncomeChallenge' WHERE `id`='VA_ADDINCOME_OTHERDESC';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='AddIncomeChallenge' WHERE `id`='VA_ADDINCOME_SOCIALSECURITY';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='AddIncomeChallenge' WHERE `id`='VA_ADDINCOME_RENTAL';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='AddIncomeChallenge' WHERE `id`='VA_ADDINCOME_PENSION';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='AddIncomeChallenge' WHERE `id`='VA_ADDINCOME_OTHERNAME';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='AddIncomeChallenge' WHERE `id`='VA_ADDINCOME_OTHER';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='AddIncomeChallenge' WHERE `id`='VA_ADDINCOME_INTEREST';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='AddIncomeChallenge' WHERE `id`='VA_ADDINCOME_ANNUITY';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='AddIncomeChallenge' WHERE `id`='VA_ADDINCOME_ALIMONY';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='AddIncomeChallenge' WHERE `id`='VA_ADDINCOME7';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='AddIncomeChallenge' WHERE `id`='VA_ADDINCOME6';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='AddIncomeChallenge' WHERE `id`='VA_ADDINCOME5';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='AddIncomeChallenge' WHERE `id`='VA_ADDINCOME4';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='AddIncomeChallenge' WHERE `id`='VA_ADDINCOME3';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='AddIncomeChallenge' WHERE `id`='VA_ADDINCOME2';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='AddIncomeChallenge' WHERE `id`='VA_ADDINCOME1';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppAddIncomeChallenge' WHERE `id`='VA_COAPP_ADDINCOME1';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppAddIncomeChallenge' WHERE `id`='VA_COAPP_ADDINCOME2';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppAddIncomeChallenge' WHERE `id`='VA_COAPP_ADDINCOME5';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppAddIncomeChallenge' WHERE `id`='VA_COAPP_ADDINCOME_ALIMONY';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppAddIncomeChallenge' WHERE `id`='VA_COAPP_ADDINCOME_ANNUITY';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppAddIncomeChallenge' WHERE `id`='VA_COAPP_ADDINCOME_INTEREST';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppAddIncomeChallenge' WHERE `id`='VA_COAPP_ADDINCOME_OTHER';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppAddIncomeChallenge' WHERE `id`='VA_COAPP_ADDINCOME_OTHERNAME';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppAddIncomeChallenge' WHERE `id`='VA_COAPP_ADDINCOME_PENSION';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppAddIncomeChallenge' WHERE `id`='VA_COAPP_ADDINCOME_RENTAL';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppAddIncomeChallenge' WHERE `id`='VA_COAPP_ADDINCOME_SOCIALSECURITY';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppAddIncomeChallenge' WHERE `id`='VA_COAPPLICANT_ADDINCOME3';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppAddIncomeChallenge' WHERE `id`='VA_COAPPLICANT_ADDINCOME4';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppAddIncomeChallenge' WHERE `id`='VA_COAPPLICANT_ADDINCOME6';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppAddIncomeChallenge' WHERE `id`='VA_COAPPLICANT_ADDINCOME7';
UPDATE `querysectionquestion` SET `ParentQuerySectionQuestion_AbstractName`='CoAppAddIncomeChallenge' WHERE `id`='VA_COAPP_ADDINCOME_OTHERDESC';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='VA_ADDINCOME1';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='VA_ADDINCOME2';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='VA_ADDINCOME3';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='VA_ADDINCOME4';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='VA_ADDINCOME5';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='VA_ADDINCOME6';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='VA_ADDINCOME_ALIMONY';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='VA_ADDINCOME_ANNUITY';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='VA_ADDINCOME_INTEREST';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='VA_ADDINCOME_OTHER';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='VA_ADDINCOME_OTHERNAME';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='VA_ADDINCOME_PENSION';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='VA_ADDINCOME_RENTAL';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='VA_ADDINCOME_SOCIALSECURITY';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='VA_ADDINCOME7';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='VA_ADDINCOME_OTHERDESC';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='VA_COAPP_ADDINCOME1';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='VA_COAPP_ADDINCOME2';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='VA_COAPP_ADDINCOME5';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='VA_COAPP_ADDINCOME_ALIMONY';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='VA_COAPP_ADDINCOME_ANNUITY';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='VA_COAPP_ADDINCOME_INTEREST';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='VA_COAPP_ADDINCOME_OTHER';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='VA_COAPP_ADDINCOME_OTHERNAME';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='VA_COAPP_ADDINCOME_PENSION';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='VA_COAPP_ADDINCOME_RENTAL';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='VA_COAPP_ADDINCOME_SOCIALSECURITY';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='VA_COAPPLICANT_ADDINCOME3';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='VA_COAPPLICANT_ADDINCOME4';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='VA_COAPPLICANT_ADDINCOME6';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='VA_COAPPLICANT_ADDINCOME7';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='VA_COAPP_ADDINCOME_OTHERDESC';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='PA_ADDINCOME1';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='PA_ADDINCOME2';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='PA_ADDINCOME3';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='PA_ADDINCOME4';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='PA_ADDINCOME5';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='PA_ADDINCOME6';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='PA_ADDINCOME7';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='PA_ADDINCOME_ALIMONY';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='PA_ADDINCOME_ANNUITY';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='PA_ADDINCOME_INTEREST';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='PA_ADDINCOME_OTHER';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='PA_ADDINCOME_OTHERDESC';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='PA_ADDINCOME_OTHERNAME';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='PA_ADDINCOME_PENSION';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='PA_ADDINCOME_RENTAL';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='PA_ADDINCOME_SOCIALSECURITY';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='PA_COAPP_ADDINCOME1';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='PA_COAPP_ADDINCOME2';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='PA_COAPP_ADDINCOME3';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='PA_COAPP_ADDINCOME4';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='PA_COAPP_ADDINCOME5';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='PA_COAPP_ADDINCOME6';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='PA_COAPP_ADDINCOME7';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='PA_COAPP_ADDINCOME_ALIMONY';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='PA_COAPP_ADDINCOME_ANNUITY';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='PA_COAPP_ADDINCOME_INTEREST';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='PA_COAPP_ADDINCOME_OTHER';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='PA_COAPP_ADDINCOME_OTHERDESC';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='PA_COAPP_ADDINCOME_OTHERNAME';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='PA_COAPP_ADDINCOME_PENSION';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='PA_COAPP_ADDINCOME_RENTAL';
UPDATE `querysectionquestion` SET `ParentQuestionOptionValue`='Yes' WHERE `id`='PA_COAPP_ADDINCOME_SOCIALSECURITY';

INSERT INTO `emailtemplates` (`TemplateName`, `TemplateText`, `Subject`, `SenderName`, `SenderEmail`) VALUES ('LoansRegistrationMessage', 'Here is the Secure code you requested in the Kony Consumer Loans: %otp%.If you did not request this, contact us at (123)-456-7890.', 'registrationMessage', 'Kony DBX', 'dbx_cl@kony.com');
